### PR TITLE
Add some explanatory text intended to help contributors run tests

### PR DESCRIPTION
**Pull request by onpaws**
Just a few small steps I had to figure out recently, hopefully helps future contributors save some time.

### CODE REVIEW

**Review by mildbyte — APPROVED** [review]
Nice, thanks! Can you link to this from the main README too so that people can find it?

**Comment by onpaws** [comment]
> Nice, thanks! Can you link to this from the main README too so that people can find it?

Good shout, added

**Comment by onpaws** [comment]
Might be nice to add a Linux-specific section in future, although it's ostensibly should be easy enough to suss out based on the macOS instructions.

Please give a shout if anything needs attention, otherwise intending to hit the green button

**Comment by onpaws** [comment]
Merging

**Pull request merged**
